name: CI
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - name: Setup go 1.16
      uses: actions/setup-go@v3
      with: {go-version: '1.16'}
    - name: Setup python 3.7
      uses: actions/setup-python@v2
      with: {python-version: '3.7'}
    - run: GO111MODULE=on go get github.com/cugu/go-resources/cmd/resources@v0.3.0 golang.org/x/tools/cmd/goimports
    - name: Checkout assets2package
      uses: actions/checkout@v3

    # stix
    - name: Checkout forensicanalysis/stixgo
      uses: actions/checkout@v3
      with:
        repository: forensicanalysis/stixgo
        path: stixgo
        ssh-key: ${{ secrets.STIXGO_DEPLOY_KEY }}
    - name: Checkout oasis-open/cti-stix2-json-schemas
      uses: actions/checkout@v3
      with:
        repository: oasis-open/cti-stix2-json-schemas
        path: cti-stix2-json-schemas
    - run: resources -trim "cti-stix2-json-schemas/schemas/" -package stixgo -output stixgo/assets.go cti-stix2-json-schemas/schemas/*/*
    - name: Commit stixgo
      run: |
        git config --global user.email "git@cugu.eu"
        git config --global user.name "Asset Bot"
        git add assets.go
        git commit -m "Update assets"
        git push origin master
      working-directory: stixgo
      continue-on-error: true

    # artifactsgo
    - name: Checkout forensicanalysis/artifactsgo
      uses: actions/checkout@v3
      with:
        repository: forensicanalysis/artifactsgo
        path: artifactsgo
        ssh-key: ${{ secrets.ARTIFACTSGO_DEPLOY_KEY }}
    - name: Checkout forensicanalysis/artifacts
      uses: actions/checkout@v3
      with:
        repository: forensicanalysis/artifacts
        path: artifacts
    - run: go run artifacts2go.go artifacts/*.yaml
    - name: Commit artifactsgo
      run: |
        git config --global user.email "git@cugu.eu"
        git config --global user.name "Asset Bot"
        git add .
        git commit -m "Update assets"
        git push origin master
      working-directory: artifactsgo
      continue-on-error: true

      # stixpy
    - name: Build python package
      run: python make_package.py
      working-directory: stix2py
    - name: Checkout forensicanalysis/pyforensicstore_stix
      uses: actions/checkout@v3
      with:
        repository: forensicanalysis/pyforensicstore_stix
        path: pyforensicstore_stix
        ssh-key: ${{ secrets.STIXPY_DEPLOY_KEY }}
    - run: mv stix2py/packaged/* pyforensicstore_stix
    - name: Commit pyforensicstore_stix
      run: |
        git config --global user.email "demian.kellermann@siemens.com"
        git config --global user.name "Asset Bot"
        git add .
        git commit -m "Update assets"
        git push origin master
      working-directory: pyforensicstore_stix
      continue-on-error: true
